### ISSUE TITLE
Add color-Parameter for Shortcode in Documentation

### ISSUE THREAD

**Issue by simondueckert** [podlove/podlove-subscribe-button#101]
In the subscribe button the color can be changed easily ([... color="#rgb"]). This info is missing in the shortcode documentation.

**Comment by benzimmer** [comment]
Depending on how you use the button in WP, please report this to either https://github.com/podlove/podlove-subscribe-button-wp-plugin/issues or https://github.com/podlove/podlove-publisher/issues. This repository is for the non-wordpress aspects of the button only.
