### ISSUE TITLE
Button does not load if it is hidden behind a wordpress menu on pageload

### ISSUE THREAD

**Issue by funkenstrahlen** [podlove/podlove-subscribe-button#103]
I use the default wordpress theme on my podcast page: http://podcast.funkenstrahlen.de/

The subscribe button is added to the sidebar and works nice on a desktop browser.

However on a smartphone the sidebar is initially hidden on pageload and can be enlarged by a hamburger menu. If I do this to show the sidebar on a smartphone the button does not get loaded and displayed.

**Comment by brototyp** [comment]
I can confirm this issue. Did you find a workaround @funkenstrahlen ?

**Comment by benzimmer** [comment]
Duplicate of #60
