### ISSUE TITLE
PocketCast Cloud Subscribe does not work

### ISSUE THREAD

**Issue by funkenstrahlen** [podlove/podlove-subscribe-button#104]
If I try to subscribe to a podcast via PocketCast Cloud. I does not work. I see this error:

![screen shot 2016-05-20 at 21 03 16](https://cloud.githubusercontent.com/assets/144173/15438838/5548af60-1ece-11e6-946b-db2452f19835.png)

**Comment by timpritlove** [comment]
It's an error caused by Pocket Casts: this message is presented for every feed that is not yet in their database. Please complain to them. It's a long-standing issue that does not make any sense as the backend allows any feed to be added manually when logged in to https://play.pocketcasts.com

**Comment by funkenstrahlen** [comment]
Ok. Thanks for the quick reply.
