### ISSUE TITLE
Pocket Casts integration broken

### ISSUE THREAD

**Issue by SimJoSt** [podlove/podlove-subscribe-button#112]
While trying how the button works, I selected Pocket Casts. Unfortunately Pocket Casts just displayed the error message:
```
The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved
```
I tried with 2 different podcasts. Here is one example link: http://pcasts.in/feed/halbwissen.co/feed/mp3/
pcasts.in in itself still works: http://pcasts.in/bitsundso

If I need to be successfully signed in to play.pocketcasts.com to make this link work, there should be a better error message. And as you cannot just change the on from pcast.in it would be nice, if the button checks for the login and then gives a more detailed error message itself.

**Comment by benzimmer** [comment]
The error message comes from Pocket Casts, not from the subscribe button so there is nothing we can do about this.

To learn more about the issue please read one of these duplicates:

- https://github.com/podlove/podlove-subscribe-button/issues/80
- https://github.com/podlove/podlove-subscribe-button/issues/95
- https://github.com/podlove/podlove-subscribe-button/issues/104

Please ask Pocket Casts support to do something about this, perhaps they'll actually change it some day.

**Comment by SimJoSt** [comment]
Thanks for responding so quickly and so informativ.

Interesting enough Pocket Casts says, it's already in their system. I checked by pasting the feed url here: http://www.pocketcasts.com/submit
Afterwards it also gives me a direct "share link": http://pca.st/6o7Q

Unfortunately I am having trouble with my Android app and cannot add any Podcasts. I cannot test that part.

I will drop them a message and join the choir of voices requesting this feature.

**Comment by benzimmer** [comment]
That is indeed strange. Please let us know if you receive an answer!

**Comment by SimJoSt** [comment]
Nearly a week later, I did not receive any answer. Twitter or email-vise.

**Comment by benzimmer** [comment]
Yes, unfortunately that was our experience too when we asked two years ago 😞

**Comment by sethiele** [comment]
Hi there the problem is still there 

```
$ curl -I https://pcasts.in/feed/freakshow.fm%2Ffeed%2Fm4a
HTTP/2 404
...
```

Is it possible to remove this service if there is no way to fix it?
