### ISSUE TITLE
Alias Pocket Casts Android to Pocket Casts Cloud

### ISSUE THREAD

**Issue by fahrradflucht** [podlove/podlove-subscribe-button#114]
I would suggest aliasing the Pocket Casts Cloud link in the Android section as long as there is no supported Android URI scheme.

While it is technically correct that this links to the cloud interface, the average user™ want's to add the podcast to the Pocket Casts Android app and the best way to do that is to go through the cloud link and click "Open in Pocket Casts" (or try the roulette that is clicking "Let device decide"). This is the exact same path one would take if she/he really wanted to use Pocket Casts Web.

Feel free to close this if this is something this was already discussed.

**Comment by saerdnaer** [comment]
@fahrradflucht Can you check if this issue was resolved by the PR?

**Comment by fahrradflucht** [comment]
@saerdnaer Fixed, thanks.
