### ISSUE TITLE
Podlove button on Android "let device decide" -> error

### ISSUE THREAD

**Issue by hzulla** [podlove/podlove-subscribe-button#115]
Hi,
- new Android device
- install AntennaPod 1.6.1.2
- http://logbuch-netzpolitik.de/abonnieren

Try Path 1:
- click "let device decide"
- "Fehler: Ein Fehler ist aufgetreten: E/A Error (java.lang.IllegalArgumentException: invalid port: -1)

Try Path 2:
- click "AntennaPod"
- works

**Comment by benzimmer** [comment]
This is most likely a bug in AntennaPod. I opened [an issue](https://github.com/AntennaPod/AntennaPod/issues/2284) there referencing this one.
