### ISSUE TITLE
Preset id instead of using a random value

### ISSUE THREAD

**Issue by mohrt-dr** [podlove/podlove-subscribe-button#116]
The id is generated as a random number. For some reasons it might be good to have an id preset to a fixed value. For us it was a caching issue but there might be other reasons too. 

We just replaced in app.js 

`Math.floor(65536 * (1 + Math.random())).toString(16).substring(1)`

with 

`this.podcast.id`

As improvement it might be better to use the value, if `this.podcast.id` is available and to use the random value otherwise.

**Comment by benzimmer** [comment]
Would it be an option for you if the JS took the button id you put on the script tag (`data-buttonid`) instead? I would prefer not polluting the podcast info with it and that would be one possible option.

**Comment by mohrt-dr** [comment]
Using data-buttonid will be perfect.

**Comment by mohrt-dr** [comment]
Just for the records the patch file for the changes of the TO comment: 
[podlove-subscribe-button-116.patch.zip](https://github.com/podlove/podlove-subscribe-button/files/521891/podlove-subscribe-button-116.patch.zip)
