### ISSUE TITLE
Bilderordner optimieren

### ISSUE THREAD

**Issue by eteubert** [podlove/podlove-subscribe-button#122]
Stelle fest, dass sich aus dem Bilder-Ordner des PSB noch viel rausholen lässt, wenn man ihn in https://imageoptim.com/mac wirft, auch bei lossless Komprimierung.

Bin aber etwas verwirrt: In `/src/images` sind viel weniger Bilder als in `/dist/images`. Sieht aus als lägen in `/src/images` nur die Originale, in `/dist/images` auch die `@1x` `@2x` `@3x` Varianten. Die scheinen aber nicht aus dem Buildprozess zu kommen, `gulp images` kopiert nur die Bilder aus `/src/images`. Heißt, man könnte einfach mal den kompletten `/dist/images` Ordner in imageoptim werfen, korrekt?

**Comment by benzimmer** [comment]
Danke für den Hinweis. Die @ Varianten waren noch Überbleibsel. Es werden einfach immer die high-res Varianten verwendet weil ich finde das das bei den Dateigrößen über die wir sprechen nicht lohnt jeweils mehrere davon zu produzieren.

Bilder sind auf jeden Fall jetzt mal durchoptimiert 😃
