### ISSUE TITLE
Button JS/CSS conflicts with window.getComputedStyle()

### ISSUE THREAD

**Issue by codecandies** [podlove/podlove-subscribe-button#129]
## Description
We have an issue with using the podlove button on our [homepage](http://www.zeit.de). To manage css breakpoints in javascript, we write an pseudo-element with the breakpoint name as content to the `body` node 

```css
body::before {
    display: none;
    content: "mobile";
}
```

and read it from javascript with 

```js
window.getComputedStyle( document.querySelector('body'), ':before' ).getPropertyValue( 'content' )
```

When the `dist/javascript/app.js` from the cdn is referenced, this construct stops working.

I tried to isolate the problem in app.js, but the only thing I could find is some IMHO not problematic code in the zepto.js used in app.js. To demonstrate the problem I made two codepens:

## Reproducing the bug
In <https://codepen.io/codecandies/pen/JrGapj?editors=1111> our logic is working, cause the `app.js` is missing: in the console the `window.getComputedStyle( document.querySelector('body'), ':before' ).getPropertyValue( 'content' )` is echoed as `'mobile'`, which is correct.

In <https://codepen.io/codecandies/pen/ZXQMBM??editors=1111>  the `app.js` from the cdn is loaded (but not used) and in the console the `window.getComputedStyle( document.querySelector('body'), ':before' ).getPropertyValue( 'content' )` is echoed as `''`, which is incorrect.

## Versions
The problem affects the actual version and we additionally use jQuery on the page.

**Comment by codecandies** [comment]
@benzimmer I added a pull request to fix our problem with www.zeit.de as it's was a problem with an outdated version of zepto.js.

**Comment by benzimmer** [comment]
@codecandies Just merged and deployed to the CDN. Could you confirm the bug is gone on your site?

**Comment by codecandies** [comment]
@benzimmer wow, that was quick. Yes I can confirm, `window.getComputedStyle( document.querySelector('body'), ':before' ).getPropertyValue( 'content' )` works as expected again on zeit.de. :)
