### ISSUE TITLE
iOS 11 Podcast App does not work anymore

### ISSUE THREAD

**Issue by sbias** [podlove/podlove-subscribe-button#131]
Since iOS 11 the link to the iOS podcast app does not work anymore "can connect".

While trying some variations i found that this subscribe-button uses pcast:// scheme to open the app. It seems that this is not working anymore. Using the scheme podcast:// fixes this issue.

**Comment by benzimmer** [comment]
Well, who cares about backwards compatibility :)

Can someone confirm that podcast:// works with the old version of the app as well. Unfortunately my only test device is on iOS11 already.

**Comment by benzimmer** [comment]
This is fixed now.

**Comment by sbias** [comment]
Works fine on iOS 10.3.3 too :)
