### ISSUE TITLE
Subscribe button not working with pocket casts cloud?

### ISSUE THREAD

**Issue by jvanvinkenroye** [podlove/podlove-subscribe-button#147]
Hi!

I tried to subscribe to a podcast (https://bldg-alt-entf.de). Clicking the subscribe button ("Abbonieren", "Weiter", "Cloud" and then "Pocket casts") brings me to "http://pcasts.in/feed/bldg-alt-entf.de/feed/m4a/" wich results in a 404 error.

Although I do not know weather this is a subscribe button issue or an issue of pocket cast clouds, I was not able to find prio information on this topic. 

Add: Tried on mac os 10.13.3 with safari 11.0.3 and chrome  65.0.3325.181

**Comment by benzimmer** [comment]
Please see https://github.com/podlove/podlove-subscribe-button/issues/112
