### ISSUE TITLE
Player.fm scheme appears to want an ID, not URL

### ISSUE THREAD

**Issue by quinncomendant** [podlove/podlove-subscribe-button#150]
The Player.fm [scheme](https://github.com/podlove/podlove-subscribe-button/blob/master/src/coffee/clients.coffee#L46) for cloud doesn't appear to work by passing a URL. For example, this doesn't work (response is a HTTP error 500):

    https://player.fm/subscribe?id=http://media.sbinstitute.com/courses/fall2012/feed.xml

However, it works fine if you give it a numerical ID:

    https://player.fm/subscribe?id=123425

It's the same scheme used as the Player.fm Android client, so I wonder if the problem occurs there too.

FWIW, I also tested with the feed URL encoded properly for the query string, same thing.

**Comment by timpritlove** [comment]
An error in the 5xx range is an internal error. So this seems to be a currently existing bug in the software.

**Comment by quinncomendant** [comment]
Right, and FWIW, this the screenshot of player.fm when it gives the error 500:

![screen shot 2018-04-16 at 17 46 38](https://user-images.githubusercontent.com/6884276/38802125-3892aa0c-419e-11e8-9de3-e361015ac7d8.png)

**Comment by timpritlove** [comment]
So I will close this for now until new information comes up.
