### ISSUE TITLE
dist folder missing in release

### ISSUE THREAD

**Issue by jzdm** [podlove/podlove-subscribe-button#152]
the [Readme](https://github.com/podlove/podlove-subscribe-button/blob/v12/README.md) says to put the folder "dist" onto your server. But since the [release v8](https://github.com/podlove/podlove-subscribe-button/tree/v8) this folder is missing.
As I only want to use the subscribe button on a website and do not want to build it and have to install all dependencies, I request to put back a pre-build version of the podlove subscribe button into the releases.
Thank you.

If I totally misunterstood how to install, please enlighten me.

**Comment by benzimmer** [comment]
We will publish new releases here from now on: https://github.com/podlove/podlove-subscribe-button/releases

**Comment by jzdm** [comment]
Excellent. Thank you very much!
