### ISSUE TITLE
Add podcast progress indicator on Android Auto App

### ISSUE THREAD

**Issue by jalbertdev** [podlove/podlove-subscribe-button#191]
I use this app with android auto a lot, but it is very difficult to tell what podcasts you have already watched when you navigate through all episodes of a podcast. Could you add a progress bar to this menu and an icon when the podcast has already been played? # #

**Comment by saerdnaer** [comment]
Can you provide a screen shot? Till then I will close this issue, as you are proably talking about another piece of software...
