### ISSUE TITLE
Subscribe - Link to pocket casts broken

### ISSUE THREAD

**Issue by mandrasch** [podlove/podlove-subscribe-button#201]
https://tenhagens-corona-podcast.podigee.io/23-hellgruen_investieren

![image](https://user-images.githubusercontent.com/777278/83726252-902b5500-a643-11ea-807e-9798cb31b062.png)

Resulting Link: https://pcasts.in/feed/tenhagens-corona-podcast.podigee.io%2Ffeed%2Fmp3
Status: 404 Error

Link without URL encoding works: https://pcasts.in/feed/tenhagens-corona-podcast.podigee.io/feed/mp3

**Comment by programmieraffe** [comment]
Confirmation of Pocket Casts that they expect non-encoded URL string:
https://twitter.com/pocketcasts/status/1286473884309450753
