### ISSUE TITLE
Procast in subscribe button (Android)

### ISSUE THREAD

**Issue by nosyjoe** [podlove/podlove-subscribe-button#211]
Name of developer: Philipp Engel
Contact information of developer: android(((-@-)))coderocker.de
Name of app: Procast
Operating System: Android
Syntax of app-specific URI for podcast subscription: procast://subscribe/
List of supported common URI schemes: pcast
High-quality image file of the icon for the app: https://www.dropbox.com/s/94019yyp3f0xyrs/logo_1024x1024.png?dl=0

Play Store: https://play.google.com/store/apps/details?id=com.podflitzer.android

Implemented in latest app version (1.4.4)

**Comment by saerdnaer** [comment]
@nosyjoe Can you create a PR against https://github.com/podlove/podlove-ui/tree/development/packages/clients/src or at least provide the content of javascript file in the correct format, similar to https://github.com/podlove/podlove-ui/blob/development/packages/clients/src/podcat/index.js – Thanks!

(You can use the same file for both android and iOS.)

**Comment by nosyjoe** [comment]
@saerdnaer thanks for the update! I did create a PR against podlove-io as suggested: 
https://github.com/podlove/podlove-ui/pull/875
