### ISSUE TITLE
Procast in subscribe button (iOS)

### ISSUE THREAD

**Issue by nosyjoe** [podlove/podlove-subscribe-button#212]
Name of developer: dsa Solutions GmbH
Contact information of developer: android(((-@-)))coderocker.de
Name of app: Procast
Operating System: iOS
Syntax of app-specific URI for podcast subscription: procast://subscribe/
List of supported common URI schemes: 
High-quality image file of the icon for the app: https://www.dropbox.com/s/94019yyp3f0xyrs/logo_1024x1024.png?dl=0

App Store: https://itunes.apple.com/de/app/procast-podcast-app/id1215380730

Implemented in latest app version (2.2.10)

**Comment by saerdnaer** [comment]
@nosyjoe Can you create a PR against https://github.com/podlove/podlove-ui/tree/development/packages/clients/src or at least provide the content of javascript file in the correct format, similar to https://github.com/podlove/podlove-ui/blob/development/packages/clients/src/podcat/index.js – Thanks!

**Comment by nosyjoe** [comment]
Done: https://github.com/podlove/podlove-ui/pull/875
