### ISSUE TITLE
Podcast Lounge Support

### ISSUE THREAD

**Issue by richardcastle** [podlove/podlove-subscribe-button#25]
◾Igneous Software Ltd.
◾support at@at igneoussoftware.com
◾Podcast Lounge
◾Windows Phone 8 / 8.1
◾podcastlounge://subscribe/<feed>
◾Nb. pcast://subscribe/<feed> scheme support included, but over-written by default Podcast app. 
◾http://windowsphone.com/s?appId=83bc0329-8e02-410e-b6d2-da3c0c1d971d

![storeicon360x360---new](https://cloud.githubusercontent.com/assets/5008685/4985745/cfbb9fb4-6930-11e4-9e57-1996362281f7.png)

**Comment by benzimmer** [comment]
Podcast Lounge was added to the list
