### ISSUE TITLE
Norwegian translation

### ISSUE THREAD

**Issue by katrinleinweber** [podlove/podlove-subscribe-button#40]
Please add/enable it for http://translate.podlove.org/collaboration/project?id=14564. I may be able to interest some people in helping, during [a workshop next week](http://apecs.is/index.php?option=com_content&view=category&layout=blog&id=802&Itemid=955&lang=en).

**Comment by benzimmer** [comment]
Done: http://translate.podlove.org/collaboration/translate/project/project/14564/language/180

**Comment by katrinleinweber** [comment]
Thanks :-)
