### ISSUE TITLE
Description in widget not wrapped in paragraph

### ISSUE THREAD

**Issue by katrinleinweber** [podlove/podlove-subscribe-button#42]
Just a very small cosmetic glitch, and I'm unfortunately not sure whether it's due to one of the [Podlove Publisher 2.0.x releases](https://github.com/podlove/podlove-publisher/commits/master) or the [Twenty Twelve 1.6](https://themes.trac.wordpress.org/ticket/22208). The description text in the PSB widget is no longer wrapped in `<p>` tags. Please compare [before](https://web.archive.org/web/20141220095416/http://www.konscience.de/) and [after](http://www.konscience.de/) these updates. If I copy the description into a WordPress text widget, it gets wrapped correctly.

**Comment by benzimmer** [comment]
I think this is an issue for the podlove-publisher. I'll open one there and reference this one.
