### ISSUE TITLE
gramcoast

### ISSUE THREAD

**Issue by klausmoster** [podlove/podlove-subscribe-button#43]
Name of developer: Klaus Moster
Contact information of developer: klaus@gramocast.net
Name of app or cloud service: gramocast
Operating System (for apps): Windows Phone
Syntax of app-specific URI for podcast subscription: gramocast://subscribe
List of supported common URI schemes: pcast:, pcast://
High-quality image file of the icon for the app/service: https://onedrive.live.com/redir?resid=58C55E46D3C0AE02%2174592

I hope the image quality is ok.

**Comment by benzimmer** [comment]
Support for gramocast has been added. Thanks for the information!

![screen shot 2015-02-20 at 11 53 28](https://cloud.githubusercontent.com/assets/164417/6284992/1d40a82c-b8f7-11e4-8592-f0ae3f505d66.png)

**Comment by timpritlove** [comment]
The correct subscription URL is actually gramocast://subscribe/

**Comment by timpritlove** [comment]
Gramocast actually hangs when the feeds gets passed over with "gramocast://"

**Comment by klausmoster** [comment]
I will add gramocast:// in the next release.
