### ISSUE TITLE
Display problems under Windows Phone 8.1

### ISSUE THREAD

**Issue by klausmoster** [podlove/podlove-subscribe-button#44]
Hi,

on Windows Phone 8.1 (Lumia 930), the podlove subscribe button works fine, but I have some bad display errors, see screenshots.

The user agent is:

Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 930) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537

![wp_ss_20150220_0005](https://cloud.githubusercontent.com/assets/11088710/6286897/da5b6c0c-b90c-11e4-9efa-6992794faedb.png)

![wp_ss_20150220_0006](https://cloud.githubusercontent.com/assets/11088710/6286898/da5c3808-b90c-11e4-9d6f-f1af1ec77a0c.png)

![wp_ss_20150220_0007](https://cloud.githubusercontent.com/assets/11088710/6286896/da5885d2-b90c-11e4-8d1f-bc6b0a6fd714.png)

Greetings,
Klaus

**Comment by benzimmer** [comment]
Hmm, that's strange. I have a 925 here, also on 8.1 and everything looks fine.
