### ISSUE TITLE
Improvement: Use fallback if given language is not supported

### ISSUE THREAD

**Issue by OpenHaus** [podlove/podlove-subscribe-button#45]
If I use the live version of the subscribe button from the CDN (https://cdn.podlove.org/subscribe-button/javascripts/app.js) and pass a language which is not supported (like French), the subscription button and all text within the pop-up stay empty.

Is there a parameter to overcome this which I missed? Otherwise a fallback language would be very handy!

**Comment by benzimmer** [comment]
Thanks for the report. The issue should now be fixed. If the passed in language is not supported it will fall back to english for now.

Could you have a look if it works as intended for you and close this if it does?

**Comment by OpenHaus** [comment]
Yes, works. Thank you!

**Comment by timpritlove** [comment]
out of curiosity: which languages did you select that were not supported and where?

**Comment by OpenHaus** [comment]
I always test in French for personal reasons. I am looking into implementing the button on podcast.de.
