### ISSUE TITLE
"&" character in the description

### ISSUE THREAD

**Issue by JoeyTheHobbes** [podlove/podlove-subscribe-button#48]
Hi!

I've come across a minor issue today:
The subscribe-button has a problem handling the "&" character in the podcast description. It's displayed as "& a m p ; " (could not write it without spaces). Other services (like iTunes) that use the same description can handle this character well though. Writing it like "& a m p ; " (without spaces) in the description itself doesn't solve the problem. I don't know if this is fixable. If yes, I'd appreciate it!
![issue](https://cloud.githubusercontent.com/assets/11300164/7371957/4011b588-edc4-11e4-9669-4b78c13736d2.png)

**Comment by benzimmer** [comment]
Thanks for noticing! This is fixed now.
