### ISSUE TITLE
Podcatcher Deluxe subscribe button

### ISSUE THREAD

**Issue by salema** [podlove/podlove-subscribe-button#51]
Name of developer: Kevin Hausmann
Contact information of developer: mail at podcatcher-deluxe.com
Name of app or cloud service: Podcatcher Deluxe
Operating System (for apps): Android
Syntax of app-specific URI for podcast subscription: pcd:// (as in Podcatcher Deluxe)
List of supported common URI schemes: pcast, rss, feed, itpc
High-quality image file of the icon for the app/service: https://raw.githubusercontent.com/salema/PodCatcher-Deluxe/master/icons/Android/deluxe/app.png

Playstore: https://play.google.com/store/apps/details?id=com.podcatcher.deluxe

Implemented in the current version 4.4

**Comment by salema** [comment]
Hi there, is there anything else I need to provide in order to make the addition happen? If that's the case, please let me know. (I already added the subscribe button to my website and its a bit strange if my own app is not listed...) Thanks and sorry if I am hurrying it too much...

**Comment by timpritlove** [comment]
Sorry, we are all very busy this week with our Podlove Workshop and a follow-up conference so we haven't found the time to test your app with our button (we want to make sure it works as advertised).

Glancing on your submission it might be valuable to clarify your URL format: is it ```pcd://<feed-url>``` or ```pcd://subscribe/<feed-url>``` (as we recommend in our documentation)?

**Comment by salema** [comment]
Thanks for the feedback, hope you have a great workshop!
I use `pcd://<feed-url>` (or `pcd:<feed-url>` for that matter) because it better fits the other schemes I support. Thanks for taking the time to look into this and for the Podlove effort in general.

**Comment by timpritlove** [comment]
Hi, I have tested with Podcatcher Deluxe and verified your URL schema works so we can add your app to the button.

However, you have submitted three different apps all using the same URL schema. We won't associate the same schema with more than one app but given the fact that these three apps seem to stem from the same code and share similar icons one entry is possibly enough anyway.

**Comment by salema** [comment]
Tim, thanks for looking into this! These are indeed three variants of the same app (the documentation says that it is appropriate to open one issue each, that's why I did so). I agree that it would be good to have one entry only - in practice hardly any user will have more than one variant installed at any point.

I usually use the icon at https://raw.githubusercontent.com/salema/PodCatcher-Deluxe/35111d87c2c13d94341f6caf983f860a064a3492/icons/all3.png to represent all three variants and the play store link should be http://play.google.com/store/search?q=pub:Kevin%20Hausmann

**Comment by benzimmer** [comment]
Podcatcher Deluxe is now in the list. Thanks for your submission!

![screen shot 2015-05-12 at 09 15 22](https://cloud.githubusercontent.com/assets/164417/7581796/73e30394-f887-11e4-9bd0-4f00d6f3ea5f.png)

**Comment by salema** [comment]
Hi Ben, thanks for adding the app to the list.
Unfortunately, the hand-over does not work for me, you used `pdc` instead of `pcd` as the scheme. Also it would be great if you could make the button use the logo and store link given above (https://github.com/podlove/podlove-subscribe-button/issues/51#issuecomment-100529907), since it would be confusing to users otherwise.
Thanks again!

**Comment by timpritlove** [comment]
Well, he had some discussion about this but have changed the icon and links for now as requested but we might revert our decision.

Problems we see: we want to keep the user experience simple and predictable. Listing an app with multiple icons is somehow breaking our concept of listing "single" apps. And we don't see ourselves in the role of providing a directory of app "variants".

Same goes for the link to the Play Store listing apps. Right now, it's just these three apps. Once you add more apps under your name to the store they also show up and might be completely unrelated.

In general, we think your app model would be much better served by using in-app-purchases but this your business alone and we don't want to argue about how you do stuff. But for our button we see conflict potential.

Maybe you can add some thoughts about this.

**Comment by salema** [comment]
Tim, I totally see where you are coming from.

If I was to start over with the apps, I might go for in-app upgrades as well. But that has some serious limitations as well, in particular on Android where you have many stores, each having their own upgrade mechanism. My current model served me well, the for-pay apps detect any installation of the free one and simply pull over the podcast list...

Anyway, thanks for changing it for now (I hope this includes the typo in the scheme?), let me know if you revert your decision. I'd also be happy to put in different schemes for each variant and have them listed individually as full apps - which they are - if that's preferable.

**Comment by timpritlove** [comment]
I can't say I would be happier if all tiny app-variations of Podcater Deluxe would be listed separately in the button. Imagine all apps on the market would do that: the list would be overly long and confusing and somehow the whole idea of making subscription simple would be contradicted. So adding different schemes for more or less the same app in (literally) three colors would be even worse.

What we *could* do (but would have to discuss internally before anyway) would be to support app variants as such by adding another level in the UI (so selecting Podcatcher Deluxe would bring up a submenu listing all variants). But right now, Podcatcher Deluxe would be the only candidate here and it would complicate our interface so I guess that is not a attractive option at this point.

So to wrap up: we'll discuss this further and might or might not return to the "link to a single app" concept ignoring variants that are basically just feature options. Not sure if you are allowed to link to the other variants in your app store description of Podcatcher Deluxe but if you can, this would be the way I'd prefer to see this work: we link to the main app and it's the app's responsibility to inform the user of other options by either allowing IAP or offering the options using other means.

I wonder if there is another way to group apps under a single Play Store link as an alternative to linking to the developer. Maybe there are other ways to tackle this.

**Comment by salema** [comment]
Agreed. I am happy with the situation as is, thanks again for including the other icon and link. There will be no further apps under the provided link in the future.

I also verified that the hand-over now works.
