### ISSUE TITLE
Video Podcatcher Deluxe subscribe button

### ISSUE THREAD

**Issue by salema** [podlove/podlove-subscribe-button#52]
Name of developer: Kevin Hausmann
Contact information of developer: mail at podcatcher-deluxe.com
Name of app or cloud service: Video Podcatcher Deluxe
Operating System (for apps): Android
Syntax of app-specific URI for podcast subscription: pcd:// (as in Podcatcher Deluxe)
List of supported common URI schemes: pcast, rss, feed, itpc
High-quality image file of the icon for the app/service: https://raw.githubusercontent.com/salema/PodCatcher-Deluxe/master/icons/Android/video/app.png

Playstore: https://play.google.com/store/apps/details?id=com.podcatcher.deluxe.video

Implemented in the current version 5.4

**Comment by benzimmer** [comment]
Closed with #51
