### ISSUE TITLE
Rendering fail is title contains percent sign ('%')

### ISSUE THREAD

**Issue by salema** [podlove/podlove-subscribe-button#54]
Adding the subscribe button to the podcast catalog at podcatcher-deluxe.com, I noticed that the button fails to render for the Podcast "99% Invisible" at http://www.podcatcher-deluxe.com/99-Invisible

Testing this further, I realized that this is *not* due to some problem with the feed or the cover image, but to the title. Removing the percent sign for testing fixed the issue. Escaping it as &#31; or using urlencode() does also fix the rendering, but has the popup dialog display the unescaped title, e.g. "99&#31; Invisible".

Is there a proper way to do this?

**Comment by benzimmer** [comment]
Thanks for reporting! It was an issue in the button code itself and is now fixed. The button now looks fine on the site too :)

Thanks for using it!

**Comment by salema** [comment]
Wow, that was fast! Thanks!
