### ISSUE TITLE
How to add CDN-hosted button?

### ISSUE THREAD

**Issue by mahemoff** [podlove/podlove-subscribe-button#57]
I've followed the instructions on the README, but not seeing the button. Please see http://jsbin.com/qejinuhopa/1/edit?html,output

**Comment by benzimmer** [comment]
You need to remove the ```data-hide="true"``` attribute. It's only meant for when you want to provide a custom element as the clickable "button".

**Comment by mahemoff** [comment]
I've done that now - http://jsbin.com/duceka/1/edit?html,output - but still not seeing it. I also tried changing the links "class" to an "id".

**Comment by timpritlove** [comment]
works for me now. reload?

**Comment by mahemoff** [comment]
Yep! Worked re-opening this in incognito. JSBin seems to have some magic caching going on. Thanks.
