### ISSUE TITLE
Title overlaps button

### ISSUE THREAD

**Issue by OpenHaus** [podlove/podlove-subscribe-button#62]
On OpenSuSE 13.2 with Firefox 38 the title ("Subscribe", "Abonnieren") is too long to fit into the small and medium button.

In the other buttons the symbol is too close to the title.

See the image.

![podlove_examples_linux](https://cloud.githubusercontent.com/assets/209948/7981036/8350bcfe-0aac-11e5-871c-66b6c500f4be.jpg)

**Comment by benzimmer** [comment]
@OpenHaus Would you be able to have a look at the Firefox Developer tools for me? Especially if there are any assets that cannot be fetched or if there are any errors displayed in the console log.

**Comment by OpenHaus** [comment]
Now it works. All resources load properly.
