### ISSUE TITLE
Button not linking to iTunes

### ISSUE THREAD

**Issue by Inrumpo** [podlove/podlove-subscribe-button#63]
Dear developpers

I found another minor issue:

![button itunes webseite](https://cloud.githubusercontent.com/assets/11300164/8085391/316a4ea8-0f90-11e5-8880-2f96fe3c0b2a.png)

The "iTunes Webseite besuchen"-Link (something like "visit iTunes website" in English) does not - as stated - link to the iTunes website. It links to the page where the subscribe button is placed in. Shouldn't it link to something like (example:) https://itunes.apple.com/us/podcast/ExamplePodcast/myPodcastID ? Or is my config somewhat wrong and I am the only one experiencing this?

**Comment by katrinleinweber** [comment]
IMHO it should.

**Comment by Strobey** [comment]
I also saw this bug and mentioned it in issue #47. As I mentioned in that bug, it only happens for "App" links. Under "Cloud" the links seem to work.
Also it's not just iTunes, it's any of the "App" subscribe types, eg. gPodder as well.

The links don't actually link to your website, it's just that the link in the code is blank. eg. the iTunes one just looks like this in the generated html: 
```html
<a href="" target="_blank"> Visit iTunes website </a>
```
In most browsers that will just go to whatever site the button is hosted on.

I've seen this in several sites, including the podlove.org one (which seems to have a broken feed btw) so it's in the core code.

**Comment by Inrumpo** [comment]
Thanks for fixing!

As a small addition/request (concerning iTunes specifically):
Users can add their own iTunes Feed ID within the Podlove options (Podlove -> Podcast Feeds -> individual Feed -> iTunes Feed ID). Instead of linking to

    https://apple.com/itunes/

Why not link to

    https://itunes.apple.com/podcast/MyiTunesFeedID/

**Comment by benzimmer** [comment]
@Inrumpo This link is there to help the user download the application, not to find the podcast representation on the iTunes directory.

**Comment by katrinleinweber** [comment]
True, but the podcast's iTunes Store page has a big banner to download iTunes itself, if it is not detected as installed (tested through TorBrowser). And "Subscribe" is also redirected to a download page. Hence a link there should not risk user confusion.

Alternatives would be renaming ` iTunes Webseite besuchen` to `iTunes herunterladen` and/or adding a 2nd link to the Store page.

**Comment by benzimmer** [comment]
I changed the wording on the link.
