### ISSUE TITLE
Broken displaying of PSB in Chrome

### ISSUE THREAD

**Issue by OhneQ** [podlove/podlove-subscribe-button#64]
If you use the Chrome browser with the navigation buttons and go one Page back and forward again, then the PSB is displayed as in the figure. And you cannot push the "abonnieren"-button. 

Thanks for fixing.

![bildschirmfoto 2015-06-10 um 07 22 25](https://cloud.githubusercontent.com/assets/12831745/8085843/91324046-0f92-11e5-8eb0-fc23f819baa6.png)
![bildschirmfoto 2015-06-10 um 07 20 35](https://cloud.githubusercontent.com/assets/12831745/8085842/9131b7de-0f92-11e5-92a4-726a06ec64bb.png)
![bildschirmfoto 2015-06-10 um 17 02 33](https://cloud.githubusercontent.com/assets/12831745/8085841/912f9f44-0f92-11e5-8d0f-10e564548fbc.png)

**Comment by benzimmer** [comment]
I can reproduce this and even get much weirder results like this (first is after first load and second is after using back/forward buttons):

![screen shot 2015-06-14 at 13 11 40](https://cloud.githubusercontent.com/assets/164417/8148299/27f5785c-1297-11e5-85ad-eccc5d8441c8.png)

![screen shot 2015-06-14 at 13 11 49](https://cloud.githubusercontent.com/assets/164417/8148295/0c634772-1297-11e5-8731-f0e09da9783b.png)

Seems like a bug in Chrome, I'll open an issue there to see if it really is.

**Comment by benzimmer** [comment]
@OhneQ On which page did you encounter the bug?

**Comment by benzimmer** [comment]
Issue on chromium bug tracker: https://code.google.com/p/chromium/issues/detail?id=500260

**Comment by OhneQ** [comment]
Well, a Listener has has made me aware of the bug.
 
I tested the following pages:
http://www.ohneQ.de
http://podlove.org/podlove-subscribe-button/
http://www.cre.fm

I can reproduce this bug only in Chrome.

**Comment by benzimmer** [comment]
Seems like they accidentally fixed this in chrome (my bugreport is still open)...
