### ISSUE TITLE
Outdated app information within subscribe button

### ISSUE THREAD

**Issue by cohan** [podlove/podlove-subscribe-button#65]
Digging around it looks like I'm unable to change the apps referenced as they're hosted on your servers.

I only know of two issues, but could the rest be double checked too?

Cloud->Instacast: Instacast has been discontinued, I'd imagine the cloud service will soon be too

Cloud->Pocket Casts: The URL to subscribe appears to be broken, returning "The page you were looking for doesn't exist"

Thank you for your time

**Comment by benzimmer** [comment]
Hi and thanks for noticing :)

Instacast will be removed from the list when it's no longer online (probably earlier, but that needs to be discussed first).

Regarding Pocket Casts, which Podcast did you try to subscribe. Unfortunately they don't have every podcast in their directory and only those that are in it really work with the URL.

**Comment by cohan** [comment]
Ah I'd not realised pcasts.in only works for shows they already know about, apologies.

**Comment by timpritlove** [comment]
Well it should work and we have an open request with Pocket Casts in that regard. Would help if you could point the developers to that problem.
