### ISSUE TITLE
"Choose App" dialog not opening on demo page

### ISSUE THREAD

**Issue by alexliebowitz** [podlove/podlove-subscribe-button#66]
The demo at http://podlove.org/podlove-subscribe-button/ seems to be broken. I tried it in Chrome, and when I click the button, it opens, but I get this JS error:
```
Uncaught TypeError: Cannot read property 'replace' of undefined (app.js: 1)
```

And when I click "Choose App", the dialog doesn't open, and I get this JS error:
```
Uncaught TypeError: Cannot read property 'moveLeft' of undefined (app.js: 1)
```

On Firefox I get the same results but different JS errors. I'm on Chrome 43.0.2357.130 m and Firefox 38.0.5.

**Comment by timpritlove** [comment]
Safari reports:

```
[Error] TypeError: undefined is not an object (evaluating 'r.replace')
	prepareClients (app.js, line 1)
	e (app.js, line 1)
	initPanels (app.js, line 1)
	t (app.js, line 1)
	openPopup (app.js, line 1)
	(anonymous function) (app.js, line 1)
	(anonymous function) (app.js, line 1)
```

**Comment by benzimmer** [comment]
This is an error in the integration, not the button itself. I will see if it's possible to catch the error and display a message to the owner of the page when he/she integrates it.

**Comment by zealot128** [comment]
Just in case for integrators having this problem: For me, it was the definition of the feed audio format:

```
feeds: {
   //...
   format: 'audio/mp3'
}
```

doesn't work, as it has to be given in the short-format ("mp3"). 

The button crashes, if none of the formats listed here are provided (https://github.com/podlove/podlove-subscribe-button/blob/1c1bec8a816d79c8682f35808458c21e0a954f23/src/coffee/clients_panel.coffee#L40).
So, make sure at least one feed-source is any of  ['mp3', 'ogg', 'aac', 'opus'].

**Comment by alexliebowitz** [comment]
Looks like the integration at http://podlove.org/podlove-subscribe-button/ is still broken. For a while it was showing the new "At least one of the feed formats is wrong" dialog, but it reverted back, probably due to Ben reverting the change in the experimental version (see #67).

**Comment by benzimmer** [comment]
Yes, it will stay broken until this is fixed: https://github.com/podlove/podlove-subscribe-button-wp-plugin/issues/6
