### ISSUE TITLE
Website shows error message "At least one of the feed formats is wrong"

### ISSUE THREAD

**Issue by jonasschoen** [podlove/podlove-subscribe-button#67]
Hello,

I use the Podlove Subscribe Button-WordPress-Plugin on my [Website](http://jonas-schoenfelder.de/podcasts/) to display two podcasts. When I go to that page I get the following error message:

![bildschirmfoto 2015-06-27 um 14 11 06](https://cloud.githubusercontent.com/assets/9519201/8391913/c707a200-1cd6-11e5-94a2-1c5dfb8cbe34.png)

I only use feeds with these four formats: 
![bildschirmfoto 2015-06-27 um 14 11 29](https://cloud.githubusercontent.com/assets/9519201/8391917/e2dc8680-1cd6-11e5-825b-7c2cec676802.png)
and
![bildschirmfoto 2015-06-27 um 14 16 09](https://cloud.githubusercontent.com/assets/9519201/8391925/1a11ee92-1cd7-11e5-8218-8302fb1a05ca.png)

I have no idea what's wrong there. I would appreciate your help. Thank you,
Jonas

**Comment by benzimmer** [comment]
Hi Jonas, it seems like the Plugin is using a wrong source for the buttons javascript code which lead to an experimental version being integrated into your site. Sorry for that! I have reverted the experimental version to a 'safe' state so it should work on your site again and will open an issue in the plugin repository to get this fixed...

**Comment by jonasschoen** [comment]
Ok, thank you!
