### ISSUE TITLE
Enable gzip on CDN for js/css resources

### ISSUE THREAD

**Issue by pgerstbach** [podlove/podlove-subscribe-button#69]
Hi,

thanks for providing your button on your CDN!

I just noticed, with help of Google PageSpeed that the javascript gzip/deflate compression is not activated on these ressources:
https://cdn.podlove.org/subscribe-button/javascripts/app.js
https://cdn.podlove.org/subscribe-button/stylesheets/app.css

I suggest to enalbe it, if possible.

Regards,
Peter

**Comment by benzimmer** [comment]
Good catch, thanks. It's now enabled!
