### ISSUE TITLE
Add PodGrasp iPhone support

### ISSUE THREAD

**Issue by GaryHughes** [podlove/podlove-subscribe-button#70]
Name of developer: Gary Hughes
Contact information of developer: support@podgrasp.com
Name of app or cloud service: PodGrasp
Operating System (for apps): iPhone
Syntax of app-specific URI for podcast subscription: podgrasp://subscribe/<feed-url>
List of supported common URI schemes: pcast://<feed-url>
High-quality image file of the icon for the app/service: http://www.podgrasp.com/img/PodGrasp_iPhone_512x512.png
Implemented in version 2.2.2

**Comment by timpritlove** [comment]
Testing fails with our subscribtion tool at <http://subscribe-test.podlove.org>. Have you tested this? PodGrasp seems to stall when loading the feed in the subscription dialogue.

**Comment by GaryHughes** [comment]
Yes, if I add podgrasp://subscribe/ to the my-uri-scheme text field I can subscribe with no issues.

**Comment by benzimmer** [comment]
I run into almost the same issue as with the Mac version (see https://github.com/podlove/podlove-subscribe-button/issues/71#issuecomment-130366257). I try to subscribe, the app opens with the subscribe dialog, crashed immediately and has the feed subscribed after re-opening it.

Also, if you need any more information, please let me know.

**Comment by benzimmer** [comment]
@GaryHughes The last update fixed the crash-bug and the app is now listed in the subscribe button.
