### ISSUE TITLE
Add PodGrasp Mac support

### ISSUE THREAD

**Issue by GaryHughes** [podlove/podlove-subscribe-button#71]
Name of developer: Gary Hughes
Contact information of developer: support@podgrasp.com
Name of app or cloud service: PodGrasp
Operating System (for apps): OSX
Syntax of app-specific URI for podcast subscription: podgrasp://subscribe/<feed-url>
List of supported common URI schemes: pcast://<feed-url>
High-quality image file of the icon for the app/service: http://www.podgrasp.com/img/PodGrasp_OSX_512x512.png
Implemented in version 2.0.1

**Comment by timpritlove** [comment]
When will version 2.0.1 be released? It's not in the store yet as it seems.

**Comment by GaryHughes** [comment]
It was released 2 days ago but it hasn't propagated to the App Store, I'm chasing it up now.

**Comment by benzimmer** [comment]
Hi,

I just tested this and it still seems to be a bit buggy. I recorded my try:

![podgrasp-test](https://cloud.githubusercontent.com/assets/164417/9230341/fbf5f678-4121-11e5-9b9d-dad9b924a7c4.gif)

In short: It never did anything than open the app when it was not already running (no subscribe was triggered). When the app was running it showed the subscribe dialog and crashed shortly afterwards. After reopening the feed was subscribed.

If you need any more information, please let me know.

**Comment by timpritlove** [comment]
Latest update 2.0.2 has fixed the problems.

**Comment by GaryHughes** [comment]
Great, thanks Tim.

**Comment by benzimmer** [comment]
PodGrasp for Mac has been added to the list of apps:

![screen shot 2015-08-28 at 10 03 10](https://cloud.githubusercontent.com/assets/164417/9541820/0dccd762-4d6c-11e5-8e63-62bc4b143265.png)

Thanks!
