### ISSUE TITLE
Add caching headers

### ISSUE THREAD

**Issue by OpenHaus** [podlove/podlove-subscribe-button#73]
Google complains that the script 'https://cdn.podlove.org/subscribe-button/javascripts/app.js' isn´t cached properly.

Nutzen Sie Browser-Caching für die folgenden cachefähigen Ressourcen:

    https://cdn.podlove.org/subscribe-button/javascripts/app.js (Ablaufdatum nicht festgelegt)

They propose the following: https://developers.google.com/speed/docs/insights/LeverageBrowserCaching

Any chance to configure the webserver to support this? Thanks!

**Comment by RobRoy** [comment]
+1

**Comment by benzimmer** [comment]
The server delivers the file with an expires header:

```
ETag: "5641c6ad-1ee30"
Expires: Tue, 17 Nov 2015 14:24:39 GMT
Cache-Control: max-age=3600
Cache-Control: public
```

The caching time is set to one hour on purpose to allow quick replacement when we update the button code.
