### ISSUE TITLE
Allow alternate iTunes activiation via URL (OSX, iOS)

### ISSUE THREAD

**Issue by timpritlove** [podlove/podlove-subscribe-button#74]
The Subscribe Button API should be extended to allow configuration of alternative invocation of iTunes using iTunes-Store-URLs instead of the default protocol scheme based approach.

Background: iTunes does not honor subscription requests done via protocol scheme properly as it does influence the iTunes Store statistics for the podcast. The solution is to use URL-based activation which causes iTunes to be invoked by the browser and to bring up the iTunes Podcast Directoy page for the podcast. The user needs then to click the iTunes subscribe button within the program making the process less seamless, but it is up to the podcaster to use either method.

In order to enable URL based acitivation for iTunes, the podcaster must provide the iTunes podcast ID (part of the URL) which the PSB can use to construct the URLs. It is better to just take the ID as a parameter to be  able to react to URL changes in the future (this has happened before).

The PSB API needs a new configuration option where a iTunes podcast ID is passed along a certain feed (this is a per-feed option).

**Comment by benzimmer** [comment]
This is now supported. Every client can now register a custom feed type. The URL will then be used for the entry in the client list panel.

This is how you would add the custom type to the button configuration:
```javascript
{
  "type": "itunes-url",
  "url": "https://itunes.apple.com/de/podcast/newz-of-the-world/id492588543"
}
```

**Comment by benzimmer** [comment]
As clarification. The final format to pass this in to the button is through an additional attribute for a feed:

```json
