### ISSUE TITLE
multiple buttons for multiple podcasts

### ISSUE THREAD

**Issue by eazyliving** [podlove/podlove-subscribe-button#75]
Hiho!

I have issues with multiple buttons for multiple podcasts. Take this page:

http://flattrboard.hoersuppe.de/list/vswcjtyupyzxborWvGlgk7slrmz3fpwgeAxr47vm

Three buttons, three podcasts. Open one (clicking  ' Abonnieren') and the screen behind blurs. To black! :O For each button on this page, the background blurs further. It's hard to explain, just try it. You also have to close the windows three times :)

What have I done? ;-) And what can I do to fix this?

[update] It's about data-hide="true". Removing the data-hide results in expected behaviour...[/update]

**Comment by benzimmer** [comment]
It only happens when using a custom button to open the popup. Seems the click handler is bound multiple times. I'll try to fix it as soon as possible.

**Comment by benzimmer** [comment]
Really sorry this took so long. The issue should now be fixed and the update is available via the CDN.
