### ISSUE TITLE
Übergabe des Feeds bei mehreren Subscribe-Buttons auf einer Seite

### ISSUE THREAD

**Issue by meszner** [podlove/podlove-subscribe-button#78]
Auf der Seite http://wissenschaftspodcasts.de/verzeichnis/ sind Podcasts gelistet und ich habe zu allen Podcasts mit Hilfe des Subscribe-Button-Plugins zu jedem Podcast einen Button angelegt. 

Bei der Auswahl »Andere App« wird auch immer der richtige Feed übergeben. Wähle ich aber eine App aus der Liste, dann wird ab dann immer der erstgewählte Podcast übergeben, auch wenn ich den Button eines anderen Podcasts auf der Seite klicke. Bis zum nächsten Refresh der Seite.

Gibt es eine Möglichkeit, den Button mehrfach zu verwenden, ohne die Seite neu zu laden?

**Comment by timpritlove** [comment]
Problem ist nachvollziehbar und scheint sich nur auf Local Apps zu beziehen. "Andere Apps" zeigt die richtige URL an und auch alle "Cloud Apps" bekommen die richtigen Daten übergeben.

**Comment by benzimmer** [comment]
Problem erkannt und behoben. Sorry, hat leider etwas länger gedauert :disappointed:
