### ISSUE TITLE
Pocket Cast Cloud link changed

### ISSUE THREAD

**Issue by funkenstrahlen** [podlove/podlove-subscribe-button#80]
If I try to subscribe to a podcast via Pocket Casts Cloud the subscribe button generates the following link:

`http://pcasts.in/feed/podperlen.funkenstrahlen.de/feed.rss`

However pcasts.in does not exists any more.

I do not know what the new link url is.

**Comment by timpritlove** [comment]
According to http://www.shiftyjelly.com/support/pocketcasts#138 this URL scheme is still valid but still seems only to work with URLs known to Pocket Casts. Should change once the URL has been subscribed by Pocket Casts at least once.

**Comment by benzimmer** [comment]
Yes, this has been an issue since the beginning and it seems they are not really willing to change it. As there is pretty little we can do about this I would close the issue for now.

@timpritlove Did you contact them about this "back in the days"?

**Comment by timpritlove** [comment]
I did. Probably time to renew our interest.

**Comment by benzimmer** [comment]
:+1: 

![w8bkz](https://cloud.githubusercontent.com/assets/164417/11977869/fc1bea18-a986-11e5-9d84-b3585feb3529.jpg)
