### ISSUE TITLE
Text and Images are not lined up

### ISSUE THREAD

**Issue by funkenstrahlen** [podlove/podlove-subscribe-button#81]
![screen shot 2015-12-23 at 21 10 53](https://cloud.githubusercontent.com/assets/144173/11984217/bc0e6ad0-a9b9-11e5-8538-04b71009090e.png)

**Comment by benzimmer** [comment]
Can you specify the URL where this happens?

**Comment by funkenstrahlen** [comment]
Has been a problem with my own site CSS. Could fix it myself.
