### ISSUE TITLE
Orthography and text smoothness

### ISSUE THREAD

**Issue by HerrvonSpeck** [podlove/podlove-subscribe-button#83]
The german text that is supposed to explain the subscription (when you click the '?') is still pretty rough and barely conforms to german orthography. I postet a better version of the text about 2 years ago. Will you ever fix this?

**Comment by timpritlove** [comment]
posted it where?

**Comment by HerrvonSpeck** [comment]
I can't find the Issue anymore. Here are the texts I wrote from my local backup:

Correct orthography:

> Ein Abonnement erlaubt einer Podcast-App neue Folgen automatisch herunterzuladen oder das Podcast-Archiv mit alten Episoden zu durchsuchen.
Der Podlove-Subscribe-Button *(hier könnten Bindestriche weggelassen werden, weil es sich um einen Eigennamen handelt)* hilft dir dabei. Wähle deine favorisierte Podcast-App aus der Liste der verfügbaren Apps oder wähle einen Podcast-Cloud-Service den du benutzt.
Beim Start sollte die Podcast-App den Podcast zur Liste der Abonnements hinzufügen. Benutze den Download-Link, um die App zu installieren, falls sie es noch nicht ist.

Relevant rules: [#41](http://www.duden.de/sprachwissen/rechtschreibregeln/fremdwoerter#K41) and [#42](http://www.duden.de/sprachwissen/rechtschreibregeln/fremdwoerter#K42)

Or you could use this one, which is a little bit more inviting for my taste:

> Dank eines Abonnements verpasst du keine Episode dieses Podcasts mehr. Nach dem Abonnieren lädt eine Podcast-App automatisch neue Folgen herunter und gibt dir Zugriff auf das Episoden-Archiv. Der *Podlove Subscribe Button* macht das Abonnieren leichter. Wähle eine App oder einen Cloud-Service aus und lasse den Button alles Weitere erledigen. Benutze den Download-Link, um die App falls nötig zu installieren.

**Comment by benzimmer** [comment]
@timpritlove Would you be OK with the alternative version?

**Comment by timpritlove** [comment]
The second version is fine with me.
