### ISSUE TITLE
Make Button customizable

### ISSUE THREAD

**Issue by partnerwerk** [podlove/podlove-subscribe-button#85]
I would appreciate simple options to customize the colors of the subscribe button either as shortcode options` [podlove-subscribe-button bg-color=#xxxxxx bg-hover-color=#xxxxxx ...]` or as option fields in the subscribe button widget.

**Comment by benzimmer** [comment]
Depending on how you use the button in WP you need to either report this to https://github.com/podlove/podlove-subscribe-button-wp-plugin/issues or https://github.com/podlove/podlove-publisher/issues. This repository is only for the basic functionality of the button, not the integration in Wordpress and the like.
