### ISSUE TITLE
PSB not offering any apps on Windows 10

### ISSUE THREAD

**Issue by Inrumpo** [podlove/podlove-subscribe-button#86]
A few days ago I switched from Windows 7 to Windows 10. When clicking the subscribe button on my Windows 10 machine, the plugin only offers me the feed address and not a single app (e.g. iTunes).

**Comment by timpritlove** [comment]
Hm. looks like we're not properly detecting win 10 yet :)

**Comment by benzimmer** [comment]
@Inrumpo Could you please have a look again? I added detection and a few clients.

**Comment by Inrumpo** [comment]
@benzimmer Thank you for fixing this. I now see:

- gPodder
- iTunes
- Podscout
- RSS

**Comment by timpritlove** [comment]
Are you missing any clients in this list?

**Comment by Inrumpo** [comment]
I don't.
However, as an iTunes user, I don't really know what could be missing. I don't know any good podcast apps for Windows.

**Comment by benzimmer** [comment]
OK, then I'll close this for now :)
