### ISSUE TITLE
Podcast Republic

### ISSUE THREAD

**Issue by benzimmer** [podlove/podlove-subscribe-button#87]
Name of developer: Podcast Republic
Contact information of developer: tech@podcastrepublic.net
Name of app or cloud service: Podcast Republic
Operating System (for apps): Android
Syntax of app-specific URI for podcast subscription: podcastrepublic://subscribe/
List of supported common URI schemes: pcast://
High-quality image file of the icon for the app/service: 

![podcast-republic](https://cloud.githubusercontent.com/assets/164417/13453846/8395b91c-e053-11e5-8100-43048f22c134.png)

**Comment by gemiren** [comment]
Notice this new app request has been opened for a long while. Is there any reason this Podcast Republic app can not be added to the supported app list? Thanks.

**Comment by timpritlove** [comment]
Thanks for pointing this out. I have just tested this with the current version and it looks as if it is working. 

Do you see anything that keeps us from adding this app, @benzimmer ?
