### ISSUE TITLE
Isolate button css from global rules

### ISSUE THREAD

**Issue by funkenstrahlen** [podlove/podlove-subscribe-button#94]
I currently face the problem that my page css destroys the button UI, because I have some rules defined for `image` for example. [See here for demo](https://podperlen.de/abonnieren/).

![screen shot 2016-04-24 at 21 25 14](https://cloud.githubusercontent.com/assets/144173/14769883/10859f5c-0a63-11e6-815d-f62ce7085c28.png)

Please isolate the button css. Could be done like this for example: http://stackoverflow.com/questions/10064172/how-to-isolate-a-div-from-public-css-styles

**Comment by timpritlove** [comment]
Well, the button is in an isolated iframe (not just a div) so this shouldn't happen (TM)

**Comment by benzimmer** [comment]
We just rolled out a new version of the button that should handle this a lot better. There are still some minor issues which we will iron out in the coming days.

**Comment by benzimmer** [comment]
Btw.: There are no clients shown in the popup because you did not provide a valid URL for the feed.

```

**Comment by funkenstrahlen** [comment]
Oh sorry, did not see that :/ You can close that.
