### ISSUE TITLE
Cloud-Subscribe for Pocketcast not working

### ISSUE THREAD

**Issue by NedNisW** [podlove/podlove-subscribe-button#95]
Hey Guys,

if you want to subscribe a podcast into pocketcast (cloud) you get the following Message:

> The page you were looking for doesn't exist.
> 
> You may have mistyped the address or the page may have moved.

**Comment by timpritlove** [comment]
Pocketcasts tends to put out these error messages if a podcast feed is not yet in the database. Do you know if the feed is already in the PocketCasts directory (aka has already been subscribed to with PocketCasts before).

Please name the Feed URL.

**Comment by NedNisW** [comment]
Heya, 

sorry :)
As i was in bed yesterday, i thought it would be a great idea to commit the feed url into the ticket.

The Podcast was http://www.kuechenstud.io/lagedernation/
Pocketcast target url: http://pcasts.in/feed/www.kuechenstud.io/lagedernation/feed/aac/

I've not subscribed this Podcast before. If you ask if i know, if anybody else before subscribed this podcast with pocketcast - i don't know.

As now i've subscribed, i also tested a few seconds ago, if it work if i'm logged out in pocketcast. But it did not work for me. Same result.

I've also googled for a description for pocketcast api/url handling in a rush, but i found nothing.

**Comment by NedNisW** [comment]
I think i missunderstood the question ;) 

No. I don't find the Podcast (by title) over the pocketcast search. Only by pasting the feed url.

**Comment by benzimmer** [comment]
This is a problem with PocketCasts that we already reported to them 2 years ago. Unfortunately there is not much we can do from our side. Still, would be nice if you perhaps could ping them on twitter or something and report this too.
