### ISSUE TITLE
Close and Help not visible in Safari

### ISSUE THREAD

**Issue by funkenstrahlen** [podlove/podlove-subscribe-button#96]
I found another weird bug in Safari. Does not happen in Chrome.

When I click subscribe on this button: http://podcast.funkenstrahlen.de/ I do not see the help and close buttons.
![screen shot 2016-04-28 at 11 23 38](https://cloud.githubusercontent.com/assets/144173/14881333/cad0fcd0-0d33-11e6-9f91-8be284dd5b24.png)

They are there though as I can click them.

If I go to the debugger and disable/enable the color of the buttons, they magically appear. Looks like a Safari rendering issue in my eyes.
![screen shot 2016-04-28 at 11 23 52](https://cloud.githubusercontent.com/assets/144173/14881356/df67ae5a-0d33-11e6-87ff-6896984be884.png)

**Comment by Fischaela** [comment]
Hey @funkenstrahlen, thanks for your bug report! I just did a quick check and it seams you're right, that there is a sort of rendering issue in Safari. I will take a deeper look at it. Maybe we can somehow trigger the rendering.

**Comment by benzimmer** [comment]
Tried in most recent Safari (10.1) and was not able to reproduce anymore.
