### ISSUE TITLE
Performance issue: app.js is loaded twice

### ISSUE THREAD

**Issue by eteubert** [podlove/podlove-subscribe-button#98]
app.js is loaded twice per page load: once on the site embedding the button, and once from inside the frame. Caching seems to not apply here (only on subsequent requests), probably because the iframe URL is different from the embedding URL?

Not sure if anything can be done about this but it's worth bringing it up at least.

<img width="872" alt="cre211_ziviler_luftverkehr___cre__technik__kultur__gesellschaft" src="https://cloud.githubusercontent.com/assets/235918/14911252/7cdb0be4-0df4-11e6-8f7f-a0eadd295ddf.png">

**Comment by benzimmer** [comment]
This only happens on the first load and the file is 271B "large", so I think it's OK here. I will enable http2 for the CDN server soon, then you don't even have the overhead of initiating the second request.
